### ISSUE TITLE
Getting "Error retrieving data!" when running "What's the spot" calculator

### ISSUE THREAD

**Issue by tgspacelabs** [flyingchipmunk/spotter#7]
We recently found that the "What's the spot" calculator on our website ([https://www.skydivesnohomish.com/Licensed_Skydivers/Whats_the_Spot.aspx](https://www.skydivesnohomish.com/Licensed_Skydivers/Whats_the_Spot.aspx)) is not working.  It responds with "Error retrieving data!"  My initial guess at the problem is a broken URL or API call.

**Comment by flyingchipmunk** [comment]
Probably a good guess. I'll take a look later this week.

**Comment by tgspacelabs** [comment]
Has there been any progress on this issue?

**Comment by flyingchipmunk** [comment]
> Has there been any progress on this issue?

Sorry been busy with other things. I'll make time this weekend to dig into this.

**Comment by flyingchipmunk** [comment]
Unfortunately it looks like NOAA has discontinued the text forecast that this tool was dependent on. Unless I can find an alternative source this essentially ends-of-life the spotter tool :(

**Comment by flyingchipmunk** [comment]
think I have some magic happening on another one of NOAA's APIs, fix coming soon!

**Comment by flyingchipmunk** [comment]
New release spun up, you can grab download link on this page:

[Spotter v1.2.3](https://github.com/flyingchipmunk/spotter/releases/tag/v1.2.3)

**Comment by runamuk0** [comment]
I've updated to the latest PHP code v1.2.3 but the map still does not display.
Please refer to [https://www.skydivesnohomish.com/PHP/spotter-1.2.3/](https://www.skydivesnohomish.com/PHP/spotter-1.2.3/)  for a sample output.

**Comment by flyingchipmunk** [comment]
What's your config file look like? can you email me directly at
matthew.veno@gmail.com
